name: Template File Sync
description: Pulls selected files from a template repo and syncs them into this repo.
author: cyberhck

inputs:
  template-repo:
    required: true
    description: Template repository in the form owner/repo (e.g. your-org/your-template-repo)
  template-branch:
    default: main
    description: Branch to pull from
  config-path:
    default: .github/.template-sync.json
    description: Path to the JSON config file
  token:
    required: true
    description: GitHub token or PAT with repo read access from template repository and write access to the current repository.

runs:
  using: composite
  steps:
    - name: Clone template repo
      shell: bash
      run: |
        REPO="${{ inputs.template-repo }}"
        # Construct full clone URL with token
        CLONE_URL="https://${{ inputs.token }}@github.com/${REPO}.git"
        git clone --depth=1 --branch "${{ inputs.template-branch }}" "${CLONE_URL}" /tmp/template-repo
    - name: Clone target repo
      uses: actions/checkout@v4
      with:
        token: '${{ inputs.token }}'
    - uses: dcarbone/install-jq-action@v3.2.0
    - shell: bash
      run: |
        jq -r '.files[]' .github/.template-sync.json | while read -r filepath; do
          src="/tmp/template-repo/$filepath"
          dest="./$filepath"

          echo "Copying: $src -> $dest"

          # Make sure destination directory exists
          mkdir -p "$(dirname "$dest")"

          # Copy the file
          cp "$src" "$dest"
        done
    - name: commit and push
      shell: bash
      run: git diff --patch
