name: Template File Sync
description: Pulls selected files from a template repo and syncs them into this repo.
author: cyberhck

inputs:
  template-repo:
    required: true
    description: Template repository in the form owner/repo (e.g. your-org/your-template-repo)
  template-branch:
    default: main
    description: Branch to pull from
  config-path:
    default: .github/.template-sync.json
    description: Path to the JSON config file
  token:
    required: true
    description: GitHub token or PAT with repo read access from template repository and write access to the current repository.
  commit-message:
    default: "chore: sync files"
    description: The title of the PR and commit message to use
  comitter:
    description: The committer name and email address in the format `Display Name <email@address.com>`. Defaults to the GitHub Actions bot user.
    default: 'GitHub <noreply@github.com>'
  target-branch:
    default: automated_sync
    description: "The branch to push to in the repository"

runs:
  using: composite
  steps:
    - name: Clone template repo
      shell: bash
      run: |
        REPO="${{ inputs.template-repo }}"
        # Construct full clone URL with token
        CLONE_URL="https://${{ inputs.token }}@github.com/${REPO}.git"
        git clone --depth=1 --branch "${{ inputs.template-branch }}" "${CLONE_URL}" /tmp/template-repo
    - name: Clone target repo
      uses: actions/checkout@v4
      with:
        token: '${{ inputs.token }}'
    - uses: dcarbone/install-jq-action@v3.2.0
    - shell: bash
      run: |
        jq -r '.files[]' ${{ inputs.config-path }} | while read -r filepath; do
          src="/tmp/template-repo/$filepath"
          dest="./$filepath"

          echo "Copying: $src -> $dest"

          # Make sure destination directory exists
          mkdir -p "$(dirname "$dest")"

          # Copy the file
          cp "$src" "$dest"
        done
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.token }}
        commit-message: ${{ inputs.commit-message }}
        committer: ${{ inputs.comitter }}
        author: ${{ inputs.comitter }}
        branch: ${{ inputs.target-branch }}
        title: ${{ inputs.commit-message }}
